### ISSUE TITLE
Removing players doesn't update the next available player number

### ISSUE THREAD

**Issue by nathanielhysong** [joshuahysong/TICompanion#11]
When you remove players then add a new one it continue to increment the Player number.

Player 1, 2, 3
Remove Player 2
Add 1
Player 1, 3, 4

**Comment by joshuahysong** [comment]
This is happening currently due to the "Player X" name string being built from the next sequential ID number. 

The starting name should instead maybe constructed by # of current players and not connected with the internal id# of the player. 

Ordering of the player names in navigation may then be an issue. Should we sort? What if some player names are edited and some are default "Player X"?

**Comment by nathanielhysong** [comment]
Maybe you could make the players' names not incremental. Find a scifi name generator then make a limit to the number of players

**Comment by joshuahysong** [comment]
I do like that idea. Only small potential issue could be confusion with the url

Currently the id is part of the url for the player page like `/players/1/stats`

I'm curious if there would be any confusion with this id number in the url potentially not matching up with the "order number" of the player in the list.

**Comment by nathanielhysong** [comment]
What is the max # of players? Make it more of a static player placeholders. Instead of it just adding players have like 8 slots of players to be added or something along those lines

Or keep it the same, but when removing a player make it an open slot, then make the option to move players between slots

**Comment by nathanielhysong** [comment]
and the ability to remove slots

**Comment by joshuahysong** [comment]
That is very true. I like that idea. Have the navigation pane pre-populated with "slots" for the players. And the user maybe clicks the slot to add a player there. The id's could then be hard-coded with the delete just removing the associated data and hiding the page.

Drag and drop between slots could be hard to implement but a fun challenge. 

I'd still want to ability to add additional slots somewhere in the case of custom games that go above the 8 player max.
